---
- name: Deploy WireGuard Server
  hosts: wireguard_servers
  become: yes
  tasks:

    - name: Ensure the system is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install WireGuard and required packages
      apt:
        name:
          - wireguard
          - wireguard-tools
          - qrencode
          - linux-headers-$(uname -r)
          - dkms
        state: present

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Ensure net.ipv4.ip_forward is enabled on boot
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv4.ip_forward='
        line: 'net.ipv4.ip_forward=1'
        state: present

    - name: Create WireGuard configuration directory
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate server private key
      command: wg genkey
      register: server_private_key

    - name: Generate server public key
      command: echo "{{ server_private_key.stdout }}" | wg pubkey
      register: server_public_key

    - name: Generate pre-shared key
      command: wg genpsk
      register: psk

    - name: Retrieve network interface with public IP
      command: ip -o addr show scope global | awk '$4 !~ /^(10|192\.168|172\.(1[6-9]|2[0-9]|3[0-1]))\./ {print $2}' | head -n 1
      register: interface_output
      
    - name: Create WireGuard server config
      template:
        src: wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        mode: '0600'

    - name: Start WireGuard interface
      command: wg-quick up wg0

    - name: Enable WireGuard to start on boot
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

### Templates

#### `wg0.conf.j2`


